[2024-10-03T15:45:40.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T15:45:41.194+0000] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: data_preparation.read_data scheduled__2024-10-03T15:15:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-10-03T15:45:41.231+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
